### ISSUE TITLE
Statement - ResultSet coupling

### ISSUE THREAD

**Issue by rodionos** [axibase/atsd-jdbc#3]
The readme needs to cover the case, that the same statement cannot be re-used to execute multiple queries. 

```java
Statement statement = connection.createStatement();
ResultSet resultSet1 = statement.executeQuery(query1);
while (resultSet1.next()) {
   //process resultset
}
ResultSet resultSet2 = statement.executeQuery(query2);
```

What error will be raised? What is the recommended pattern?
Actually, we could automatically close `resultSet1` once we reach the last row to allow this kind of use case?

**Comment by raipc** [comment]
Now this is a valid pattern. ResultSet gets closed automatically when the cursor reaches the last row, also ResultSet gets closed if a new executeQuery method is executed. This seems to be a common behavior. For example, the following code in Postgres will throw an exception `org.postgresql.util.PSQLException: ResultSet закрыт.`: 

```
ResultSet resultSet = statement.executeQuery("select * from test");
resultSet.next();
ResultSet resultSet2 = statement.executeQuery("select * from test");
resultSet.next()
```

**Comment by rodionos** [comment]
Sounds good, closing.
