### ISSUE TITLE
ATSD supports default SQL wildcards now

### ISSUE THREAD

**Issue by raipc** [axibase/atsd-jdbc#31]

**Comment by rodionos** [comment]
Does it impact the jdbc driver? INSERT code?

**Comment by raipc** [comment]
I created the issue to remember to revise the code if there are mentions of old wildcards in tests, metadata, or documentation.
Now I have a question about `tables` connection string parameter. We never describe its syntax (just call it 'metric expression', but is neither the expression that we use in Series API, nor SQL wildcard expression). Since we support standard SQL wildcards in ATSD, should we use the same wildcards in `tables` connection string parameter or document current syntax.

**Comment by rodionos** [comment]
The wildcards in getTables and getColumns methods should be % and _. This is how it's implemented in other databases. Likewise, the wildcard in `tables=` needs to be modified to % and _.

**Comment by rodionos** [comment]
Looks like we're already using standard wildcard, per issue 4395.

**Comment by raipc** [comment]
We use standard wildcards in DatabaseMetadata methods, but asterisk and question mark in `tables` connection string property

**Comment by rodionos** [comment]
For consistency, I would use SQL wildcard in tables= property as well.
