### ISSUE TITLE
atsd_entity column type is varchar for numeric type

### ISSUE THREAD

**Issue by rodionos** [axibase/atsd-jdbc#65]
Driver version 1.4.8 (we don't have 1.4.9 on maven)

```
SELECT tags.symbol, tags.class_code, tags.lot AS LONG FROM atsd_entity WHERE tags.symbol = 'LKOH' limit 1
```

The third column getColumnTypeName returns varchar, ignoring the cast.

Server metadata is:

```
"tags.symbol","tags.class_code","LONG"
"LKOH","EQRD","1"
```

![image](https://user-images.githubusercontent.com/2098022/114182544-67eb4180-994b-11eb-9092-077eab72c94e.png)

**Comment by raipc** [comment]
@rodionos 
Please, try the following query:

```
SELECT tags.symbol, tags.class_code, CAST(tags.lot AS number) FROM atsd_entity WHERE tags.symbol = 'LKOH' limit 1
```

Without `CAST`, `AS` assigns a column alias

**Comment by rodionos** [comment]
Indeed, my mistake. Related issue, with getString returning the value with fractions:

```
CAST(tags.lot AS INTEGER) AS lot

rs.getString(3) - returns 1.0
```

**Comment by rodionos** [comment]
```
SELECT datetime, trade_num, price, quantity, side FROM atsd_trade
```

```
getString(1) returns truncated time
2021-04-08 07:00:03
```

**Comment by rodionos** [comment]
Is there a way to get precise trade datetime, including microseconds?

**Comment by raipc** [comment]
> Indeed, my mistake. Related issue, with getString returning the value with fractions:
> 
> ```
> CAST(tags.lot AS INTEGER) AS lot
> 
> rs.getString(3) - returns 1.0
> ```

I will fix it in ATSD by returning correct datatype in metadata. Now `double` is returned in any case.

BTW, shouldn't we support all known numeric datatypes in CAST expression? Currently only `number`, `integer`, `float` are supported.

**Comment by raipc** [comment]
> Is there a way to get precise trade datetime, including microseconds?

Could you try with latest version 1.4.9, please?

**Comment by rodionos** [comment]
Only 1.4.8 is available on mavencentral:

```
<dependency>
    <groupId>com.axibase</groupId>
    <artifactId>atsd-jdbc</artifactId>
    <version>1.4.8</version>
</dependency>
```

**Comment by rodionos** [comment]
https://mvnrepository.com/artifact/com.axibase/atsd-jdbc - here only 1.4.8 is listed

**Comment by raipc** [comment]
> https://mvnrepository.com/artifact/com.axibase/atsd-jdbc - here only 1.4.8 is listed

Index is not updated yet, but the jar should be available
https://search.maven.org/artifact/com.axibase/atsd-jdbc/1.4.9/jar

**Comment by rodionos** [comment]
`datetime` works ok with the 1.4.9 downloaded from Releases, although I would return `time` column with fractions as well.

**Comment by raipc** [comment]
> `datetime` works ok with the 1.4.9 downloaded from Releases, although I would return `time` column with fractions as well.

Same, should be working without driver upgrade when correct metadata is returned

**Comment by raipc** [comment]
@rodionos Could you try with [latest snapshot](https://github.com/axibase/atsd-jdbc/releases/download/RELEASE-1.4.10/atsd-jdbc-1.4.10-SNAPSHOT-DEPS.jar) on latest ATSD, please?

**Comment by raipc** [comment]
Version number increase required because ATSD may send general `number` type as metadata. JDBC driver didn't recognized it and used varchar fallback. Since 1.4.10, number is alias for decimal in JDBC driver

**Comment by rodionos** [comment]
I don't see this error on the 1.4.9 version, closing.
