### ISSUE TITLE
Retrieving statement metadata for parameterized queries

### ISSUE THREAD

**Issue by raipc** [axibase/atsd-jdbc#7]
Current implementation of PreparedStatement#getMetadata() in master uses /api/sql/meta without modifying the query. If the query contains placeholder symbols, ATSD returns error. How should this case be resolved?
* Cut the query starting with WHERE condition. It will help for some simple software-generated queries.
* Implement smart query processing in JDBC driver
* Support prepared statements in ATSD level
* Something other?

**Comment by rodionos** [comment]
> Support prepared statements in ATSD level

That's the right way to do it. Raise a feature ticket with Alex T.

**Comment by raipc** [comment]
Seems working
